### ISSUE TITLE
Question: which version of the app to install? Objective-See or Digita Security?

### ISSUE THREAD

**Issue by JayBrown** [objective-see/DoNotDisturb#11]
This is all very confusing: both apps are free, but they have different version numbers, Objective-See is currently at v1.2.2, and Digita at v1.2.3.

As the developer of the original tool, which version do you suggest the user should install?

**Comment by ppseprus** [comment]
There's also a repo for issues under Digita Security, called DND-Issues (https://github.com/DigitaSecurity/DND-Issues)

**Comment by JayBrown** [comment]
Thanks. I'll ask there too.

**Comment by ppseprus** [comment]
This has been answered by @josh-stein on DigitaSecurity/DND-Issues#31.
