### ISSUE TITLE
Availability of iOS Companion App

### ISSUE THREAD

**Issue by ykv-name** [objective-see/DoNotDisturb#6]
Is it feasible to make it available in iOS App stores worldwide?

**Comment by objective-see** [comment]
Aloha, the iOS application was submitted to the iOS App Store and set to "make available to all regions" 
...so (in theory) it should be available world-wide. 

If you search for 'Do Not Disturb Companion' does it come up?
![DND iOS App](https://objective-see.com/images/DND/appStore.png) 

If not, maybe trying the  [direct link](https://itunes.apple.com/us/app/do-not-disturb-companion/id1345055731?mt=8) will help ( [https://itunes.apple.com/us/app/do-not-disturb-companion/id1345055731?mt=8](https://itunes.apple.com/us/app/do-not-disturb-companion/id1345055731?mt=8) )

**Comment by ykv-name** [comment]
Thank you for swift reply and **solved**.

It seems, as you suggest, that input of the _full title_ is needed for the correct search result to make an appearance. **Much obliged**.

**Comment by emaba** [comment]
It's not available in Italy. Could you please check? Thank you.

**Comment by Stichoza** [comment]
Same here, not available in Georgia (country 🇬🇪)

**Comment by Styrmist** [comment]
Same in Ukraine. Not available

**Comment by Nikoroma** [comment]
Same in Greece. Not available
![Screen Shot 2021-10-16 at 20 23 57](https://user-images.githubusercontent.com/92644751/137596774-edd60306-b46c-444c-b3f1-74686ae515ab.png)

**Comment by Saoznei** [comment]
Not available in France 🇫🇷

**Comment by aihkas** [comment]
Not available in Sweden unfortunately.

**Comment by eliegkassouf** [comment]
Not Available in Canada as well!

**Comment by Stichoza** [comment]
Clearly not available on the whole planet. Can anyone check on Mars? ☄️🛸 @nasa-jpl

**Comment by aihkas** [comment]
> Clearly not available on the whole planet. Can anyone check on Mars? ☄️🛸 @nasa-jpl

According to the official docs [Do Not Disturb User Guide](https://digitasecurity.com/donotdisturb/userguide/): **the DND app will no longer be supported.**

**Comment by gpakosz** [comment]
What's the status of this please?

I installed DND `1.3.0` and it prompts to install the companion app which isn't available in France

Thank you

**Comment by ksbex** [comment]
> > Clearly not available on the whole planet. Can anyone check on Mars? ☄️🛸 @nasa-jpl
> 
> According to the official docs [Do Not Disturb User Guide](https://digitasecurity.com/donotdisturb/userguide/): **the DND app will no longer be supported.**

Thanks for finding this.  Perhaps the DND download page should be updated to reflect this info so people (like me) don't waste a bunch of time trying to track this down.  It still acts like this is totally a legit app and not abandonware.

**Comment by dstorozhuk** [comment]
What if DND it self if malware? 
not fix from deveper fir 2. - it looks strange
