### ISSUE TITLE
Option to Take Photo by Default

### ISSUE THREAD

**Issue by lucascantor** [objective-see/DoNotDisturb#7]
## Problem
- The `Camera` option to take a photo from the iOS app is only available to use manually.
- This is only useful if the notification is seen before the person who opened the lid is gone.

## Proposed Solution
- Offer an option to take a photo by default, soon after the lid opening has been detected.

**Comment by objective-see** [comment]
Agreed! Will add this configurable feature
...tracking this in the companion iOS App as well: [https://github.com/DigitaSecurity/DND-Issues/issues/14](https://github.com/DigitaSecurity/DND-Issues/issues/14)

**Comment by aaronraimist** [comment]
@lucascantor why did you close the issue? As far as I can tell this was never implemented.

**Comment by lucascantor** [comment]
@aaronraimist I don’t remember closing this. It may have been a mistake.

**Comment by lucascantor** [comment]
I'm going to close this again to clean up my open issues, as this project hasn't been touched in 4 years.
