### ISSUE TITLE
Support automated installs

### ISSUE THREAD

**Issue by akerl** [objective-see/DoNotDisturb#9]
Howdy!

I'm trying to write a Homebrew Cask for installing this, and it seems like invoking `Do Not Disturb Installer.app/Contents/MacOS/Do Not Disturb Installer --install` still pops open the GUI w/ the install button.

Not sure if I'm just passing the wrong open (I stole the --install arg from the Cask for BlockBlock), or if non-interactive installs just aren't yet supported.

Thanks for all the awesome tools you've released!

**Comment by zbeekman** [comment]
Isn't this resolved? I just installed via homebrew-cask. Unless I'm missing something.

It looks like the flag needed was `-install`. The uninstall script (or adding a zap stanza) could use some love to more closely match the uninstall directions on the objective-see website...
